version: 0.0
os: linux
files:
  - source: /DSCC_CW1_5267_API/
    destination: /var/www/DSCC_CW1_5267_API
  - source: scripts/DSCC.conf
    destination: /etc/httpd/conf.d/
  - source: scripts/DSCC.service
    destination: /etc/systemd/system/

hooks:
  ApplicationStop:
    - location: scripts/stop_service
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/remove_application
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_service
      timeout: 300
      runas: root
    
